### ISSUE TITLE
Guidelines for Usage of Cloud Compute to avoid idle costs

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#109]
Work out process so people don't forget to leave idle servers on AWS / cloud compute, or a cleanup process to come back and turn these servers off if left unused. Cloud compute only makes sense if used for elastic, bursty usage <20-30% of the time, while mostly staying off. If going to keep e.g., a database server usually on >50% of the time, then we should just pay for a dedicated instance.

**Comment by jonc101** [comment]
Noticed RDS instances ron-db and healthrex-db-low-perf were idling (looks like many days).
I went ahead and stopped them, but seems we need a better process than expecting people to remember to terminate idle servers. 
I don't know how to tell, but should also find out what is the cost of leaving an EC2 or RDS server in the "stopped" rather than terminated state. I can foresee a lot of stopped servers being forgotten and left to rot as well. What should our process be to decide on killing these instances completely.

[ ] I think you mentioned a Slack channel for anyone using AWS. Add me if that's already created. Can then at least use as an announcement platform to alert anyone to declare ownership of a running server (before they get terminated if no response).

**Comment by SanthoshBala** [comment]
One idea I've toyed with is building some modules which manage (1) defining a batch process you want to run, (2) spawning N RDS and EC2 instances, (3) running batch process on those, and (4) killing RDS and EC2 instances after that's done. That way, no body has to worry about manually creating/managing/deleting them.

Also think it's worth investing in making the DB setup process a little more streamlined so that there's less of a need to use the remote DB instance.

**Comment by SanthoshBala** [comment]
RDS has a complicated pricing structure, but for us these are the main two factors [1]:
• base price per running hour: $0.365 – $1.461 per hour for the instance classes we're using
• storage: $0.10 per GB per month, so roughly $10 per DB per month
[1] https://aws.amazon.com/rds/faqs/#billing

EC2 has a similar structure [2]:
• base price per running hour: $0.02 – $0.80 per hour for the instance classes we're using
• storage: $0.10 per GB per month, so roughly $5 per instance per month
[2] https://aws.amazon.com/ec2/faqs/

In both cases, the storage price is going to be a non-trivial % of the cost (20-50%), so we should probably encourage ourselves to minimize the # of stopped instances.

**Comment by SanthoshBala** [comment]
Here's a smattering of policy ideas.
We could start out enforcing these manually, and build tools to enforce if we think it's worth it.

Running --> Stopped
• If an EC2 instance is idle for 1.5 consecutive hours (<0.5 CPU utilization), stop it
• If an RDS instance is idle for 3 consecutive hours (0 connections), stop it

To actually enforce this, we might want to set up some alerts to email one of us, or maybe just set the expectation that I check on these once a day (only takes a few minutes).

Stopped --> Terminated
• If an EC2 instance is stopped for 7 consecutive days, create a snapshot and terminate it
• If an RDS instance is stopped for 14 consecutive days, create a snapshot and terminate it

Snapshots
• On the first of each month, audit all EC2 and RDS snapshots, and delete any unnecessary ones

@jonc101 – thoughts?

**Comment by jonc101** [comment]
Basic ideas seem right.
I tried setting up alerts for idle RDS, though didn’t work the way I expected (when the instance is STOPPED, the alert would fire, complaining that the instance had 0 connections).

Could probably tighten the Stopped-Terminated threshold (3-7 days?). As long as there are snapshots, people can always just reinstantiate without much difficulty.

Seems like common utility is to get an RDS up available for general purpose queries. Is it worth it to get a reserved instance (or otherwise buy a server or server time) to keep one basic version always on? Good for regular, small queries, but not for repeated intensive queries.

Jonathan

**Comment by SanthoshBala** [comment]
Hmm, seems like with Amazon Dynamo, we could get 25 reads/sec and 25 writes/sec for free, and only pay for $0.25 per month beyond 25 GB. Even if the database grows to 100GB, that's only $20/month guaranteed, and Dynamo will handle autoscaling read capacity up/down as necessary.

That might actually be our best bet.

**Comment by jonc101** [comment]
But this looks like a NoSQL implementation. I assume we’d need a general RDS instance?

Jonathan

**Comment by jonc101** [comment]
Kill instances and save snapshots if not using them!
