### ISSUE TITLE
Patch Wilkes Barre Antibiogram Data

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#110]
Per Jill O'Donnells message:
"Instead of Staphlococcus aureus (all), I believe this should read Staphylococcus aureus (MSSA).  Is there any way the name could be changed and then combine the two to include Staphylococcus aureus (all)?"

**Comment by mrlsdvd** [comment]
Done. We'll just have to ask Jill what she expects in the combined group.
