### ISSUE TITLE
Order Set Data converter - Ignore case on Section / Subgroups

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#134]
Otherwise end up with meds getting listed twice for no reason
For example: ED PNEUMONIA lists Albuterol-Ipratropium twice under MEDICATIONS and Medications

OrderProc and OrderMed conversion scripts should each respectively adjust for these.

**Comment by ynodir** [comment]
- [x] `order_med` conversion
- [ ] `order_proc` conversion

**Comment by ynodir** [comment]
Shows differences in subgroup naming:
```
select protocol_id, ss_section_id, ss_sg_key, min(protocol_name), max(protocol_name), min(ss_section_name), max(ss_section_name), min(ss_sg_name), max(ss_sg_name), count(*) as cnt
from `starr_datalake2018.med_orderset` 
group by protocol_id, ss_section_id, ss_sg_key
having lower(min(protocol_name)) <> lower(max(protocol_name)) or lower(min(ss_section_name)) <> lower(max(ss_section_name)) or lower(min(ss_sg_name)) <> lower(max(ss_sg_name))
order by cnt desc;
```

**Comment by ynodir** [comment]
For STARR `order_med` conversion using <`protocol_id`, `ss_section_id`, `ss_sg_key`> as a unique key for `item_collection` table, so subsequent orderset rows with the same key are ignored meaning that the first encountered `protocol_name`, `ss_section_name` and `ss_sg_name` are used.

**Comment by ynodir** [comment]
For STARR `order_proc` conversion using <`protocol_id`, `ss_section_identifier`-`ss_sg_key` > as unique key for `item_collection` table, where `ss_section_identifier` is `ss_section_id` if it's not `None`, otherwise `lower(ss_section_name)`.
