### ISSUE TITLE
Make a figure 1 draft for LabChangePrediction writeup

### ISSUE THREAD

**Issue by raikens1** [HealthRex/CDSS#144]
These tasks are important:
- [x] Set up LabChangePredictionPipeline to generate data quickly and consistently #135
- [x] Run LabChangePredictionPipeline for several different test types #140 
- [x] Work on a backend analysis script (in R?) to process results

**Comment by SanthoshBala** [comment]
re: analysis script. Check out LabNormalityReport. It analyzes the raw
output of LabNormalityPredictionPipeline and generates the tables + figures
that ultimately went into that paper. Might be worth doing a similar thing
(either in R or Python)
