### ISSUE TITLE
Load RDS Database contents into an EC2 run instance, to facilitate rapid queries batch jobs (remove network IO traffic from EC2-RDS)

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#148]
EC2 database instances already loaded, but appears that the database indexes didn't get copied/loaded.

[ ] Run database index creation and the recreate EC2 image for stride-inpatient-2008-2017 data

**Comment by jonc101** [comment]
Update configuration to have more stuff already setup
pip install sklean
add to .bash_profile
sudo service postgresql96 start

**Comment by raikens1** [comment]
Would be great to also install updated matplotlib!

In an ideal world, we could have an ec2 instance with medinfo that passes all of the CDSS unittests.  We'd need to upkeep it though as CDSS continues to grow.

**Comment by jonc101** [comment]
Yes, that's exactly the idea behind unit test suite. Should always be running all tests in the whole code repo and verifying everything okay before committing code changes.
We were at such a stable state several months ago, but looks like some "regression" (particularly for different dev environments).

For matplotlib, Rocky, can you add notes here from the stackoverflow or whatever page we found.
- Remove the yum install: sudo yum remove python27-matplotlib
- sudo PATH=$PATH pip install --upgrade ...??? or something, which included not only matplotlib, but some other python-devel libraries or something.

**Comment by sxu11** [comment]
Built indexes for the raw stride_XXX table and the processed clincal_item tables. See stride/psql/indices/build_indices.log and stride/clinical_item/psql/indices/build_indices.log for details. 
Other detailed updates: have sklearn installed; filled in 'NA' for base_name when component_name='SODIUM'; updated column name "shifted_dt_tm" --> "shifted_record_dt_tm". 
The new AMI is saved as "stride-inpatient-2008-2017-postgresql-indexed". If there is no issue with it within a period of time (1 month?), gonna delete the old stride-inpatient-2008-2017-postgresql AMI.
