### ISSUE TITLE
Use AHRQ's Clinical Classifications Software as a more up-to-date way to aggregate ICD9 and ICD10 diagnosis codes

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#153]
Have Charlson Comorbidity groups methods currently, but only maps ICD9 codes, and somewhat out of date

Added AHRQ_ccsr dataset to mining-clinical-decisions project 

- [ ] Keep a mapping and citation info in medinfo/dataconversion/mapdata for additional flexibility

- [ ] Add similar mapping table for Charlson comorbidities to BigQuery database

**Comment by JonathanChiang** [comment]
seems to  require cleaning icd10 codes
