### ISSUE TITLE
STRIDE Inpatient 2008-2017 Loading Process

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#168]
Looks like some data files not present in shared Box folder.
[ ] E.g., Running restore_stride script yields file not found errors for  stride_admit_vital.dump.sql.gz, culture_micro, admit, drg, flowsheet, insurance.

[ ] Also generates errors for "role sbala does not exist." Check what the dump files are trying to do here (probably grant sbala certain table permissions), and assess implication of leaving those as skipped errors.

**Comment by SanthoshBala** [comment]
Updated tables, files, and setup instructions: https://github.com/HealthRex/CDSS/wiki/STRIDE-Database
