### ISSUE TITLE
Batch unit test failures - Some library dependencies and floating point checks

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#170]
======================================================================
ERROR: medinfo.dataconversion.test.TestEventDigraph (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: medinfo.dataconversion.test.TestEventDigraph
Traceback (most recent call last):
  File "C:\Dev\Python27\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Dev\Python27\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "C:\HealthRex\CDSS\medinfo\dataconversion\test\TestEventDigraph.py", line 6, in <module>
    import networkx as nx
ImportError: No module named networkx

======================================================================
ERROR: test_dataConversion (medinfo.dataconversion.test.TestSTRIDEDxListConversion.TestSTRIDEDxListConversion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\HealthRex\CDSS\medinfo\dataconversion\test\TestSTRIDEDxListConversion.py", line 60, in setUp
    (dataItemId, isNew) = DBUtil.findOrInsertItem("stride_dx_list", dataModel, retrieveCol="pat_id" );
  File "C:\HealthRex\CDSS\medinfo\db\DBUtil.py", line 682, in findOrInsertItem
    cur.execute( searchQuery, searchParams );
ProgrammingError: column "dx_icd10_code_list" does not exist
LINE 8: AND dx_icd10_code_list = ''
            ^

======================================================================
ERROR: test_dataConversion_maxMixtureCount (medinfo.dataconversion.test.TestSTRIDEPreAdmitMedConversion.TestSTRIDEPreAdmitMedConversion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\HealthRex\CDSS\medinfo\dataconversion\test\TestSTRIDEPreAdmitMedConversion.py", line 249, in test_dataConversion_maxMixtureCount
    self.converter.convertSourceItems(convOptions);
  File "C:\HealthRex\CDSS\medinfo\dataconversion\STRIDEPreAdmitMedConversion.py", line 48, in convertSourceItems
    rxcuiDataByMedId = self.loadRXCUIData(conn=conn);
  File "C:\HealthRex\CDSS\medinfo\dataconversion\STRIDEPreAdmitMedConversion.py", line 81, in loadRXCUIData
    DBUtil.execute(query)
  File "C:\HealthRex\CDSS\medinfo\db\DBUtil.py", line 261, in execute
    cur.execute( query, parameters )
ProgrammingError: syntax error at or near "NOT"
LINE 4:                 ADD COLUMN IF NOT EXISTS
                                      ^

======================================================================
ERROR: test_dataConversion_normalized (medinfo.dataconversion.test.TestSTRIDEPreAdmitMedConversion.TestSTRIDEPreAdmitMedConversion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\HealthRex\CDSS\medinfo\dataconversion\test\TestSTRIDEPreAdmitMedConversion.py", line 124, in test_dataConversion_normalized
    self.converter.convertSourceItems(convOptions);
  File "C:\HealthRex\CDSS\medinfo\dataconversion\STRIDEPreAdmitMedConversion.py", line 48, in convertSourceItems
    rxcuiDataByMedId = self.loadRXCUIData(conn=conn);
  File "C:\HealthRex\CDSS\medinfo\dataconversion\STRIDEPreAdmitMedConversion.py", line 81, in loadRXCUIData
    DBUtil.execute(query)
  File "C:\HealthRex\CDSS\medinfo\db\DBUtil.py", line 261, in execute
    cur.execute( query, parameters )
ProgrammingError: syntax error at or near "NOT"
LINE 4:                 ADD COLUMN IF NOT EXISTS
                                      ^

======================================================================
FAIL: test_addTimeCycleFeatures (medinfo.dataconversion.test.TestFeatureMatrixFactory.TestFeatureMatrixFactory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\HealthRex\CDSS\medinfo\dataconversion\test\TestFeatureMatrixFactory.py", line 447, in test_addTimeCycleFeatures
    self.assertEqualList(resultMatrix[2:], expectedMatrix)
  File "C:\HealthRex\CDSS\medinfo\common\test\Util.py", line 142, in assertEqualList
    self.assertEqual(verifyItem, sampleItem)
AssertionError: Lists differ: ['-789', '-900', 'LABMETB', '2... != ['-789', '-900', 'LABMETB', '2...

First differing element 6:
'0.866025403784'
'0.8660254037844388'

  ['-789',
   '-900',
   'LABMETB',
   '2009-05-06 15:00:00',
   '0',
   '5',
-  '0.866025403784',
+  '0.8660254037844388',
?                 ++++

-  '-0.5',
+  '-0.4999999999999998',
   '15',
-  '-0.707106781187',
+  '-0.7071067811865471',
?                 +++ +

-  '-0.707106781187']
+  '-0.7071067811865479']
?                 +++ +

======================================================================
FAIL: test_buildFeatureMatrix_multiFlowsheet (medinfo.dataconversion.test.TestFeatureMatrixFactory.TestFeatureMatrixFactory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\HealthRex\CDSS\medinfo\dataconversion\test\TestFeatureMatrixFactory.py", line 405, in test_buildFeatureMatrix_multiFlowsheet
    self.assertEqualList(resultMatrix[2:], expectedMatrix)
  File "C:\HealthRex\CDSS\medinfo\common\test\Util.py", line 142, in assertEqualList
    self.assertEqual(verifyItem, sampleItem)
AssertionError: Lists differ: ['-789', '-900', 'LABMETB', '2... != ['-789', '-900', 'LABMETB', '2...

First differing element 40:
'0.666666666667'
'0.6666666666666666'

Diff is 702 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_build_FeatureMatrix_multiLabTest (medinfo.dataconversion.test.TestFeatureMatrixFactory.TestFeatureMatrixFactory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\HealthRex\CDSS\medinfo\dataconversion\test\TestFeatureMatrixFactory.py", line 345, in test_build_FeatureMatrix_multiLabTest
    self.assertEqualTable(resultMatrix[2:], expectedMatrix)
  File "C:\HealthRex\CDSS\medinfo\common\test\Util.py", line 172, in assertEqualTable
    self.assertEqual(verifyItem, sampleItem)
AssertionError: '0.666666666667' != '0.6666666666666666'

----------------------------------------------------------------------
Ran 122 tests in 97.337s

FAILED (failures=3, errors=4)

**Comment by SanthoshBala** [comment]
Gonna assign this to myself. I fixed some of the trivial issues, but looks like there's a problem because some of the table field names changed between the old and new data. I was inconsistent about which name to persist, which means there is potentially conflict with the application code =(

Need to think about the lowest friction way to solve these (likely just updating the schema definitions).

**Comment by SanthoshBala** [comment]
But the StrideDxListConversion test illustrates that people will need to update their schemas in general - that failure comes from the fact that there's a new field in the data (the ICD10 code).

**Comment by jonc101** [comment]
Yes, in some cases it is the "application" that is mistaken, not the test.
E.g., Schema of test database should be updated to accommodate the changes.
Looks like some of the SQL commands (IF NOT EXISTS) are not available in PostgreSQL 9.3 that I have installed, so I'm trying to update my databases to 9.6.
I'm still working on patching the 2008-2017 dump (needs indices as part of restore), and I'm going to do some more manual tweaks of the "analysis_status" and "default_recommend" corrections.

**Comment by jonc101** [comment]
I'll try to restructure so that DBTestCase first step is to create a blank database to work with and respective test cases have to make a call to a respective Data Loader to create/prepare the relevant schema. Adds some overhead, but makes unit tests more self contained. Risk of tearDown step accidentally dropping a production database, so will try to add the step above where test case will only drop a database it was able to create itself.

**Comment by jonc101** [comment]
I cleaned up some of the database version issues, and moved the EventDigraph dependency question to a separate issue #174.
Several tests in FeatureMatrixFactory are failing because of floating point equivalence errors. There are options like assertEqualTable( expected, actual, precision=5 ), with the precision option specifying to compare floating point numbers by only 5 significant digits. However, even this does not work simply, because the FeatureMatrixFactory is comparing the results TEXT files, so is doing direct text comparisons ("0.666666" different than "0.666667"). Needs some a little more sophistication to parse these into numerical values for floating point comparison checks.

**Comment by jonc101** [comment]
Just committed major overhaul to all test cases using DBTestCase (depends on test database to interact with). Now each individual test responsible for setting up database from scratch (including what schema is needed / expected).
