### ISSUE TITLE
Run Lab Normality Prediction pipeline on common panel component results

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#176]

**Comment by jonc101** [comment]
Base names and descriptions of the component labs for the most common "daily labs" ordered in the hospital (basic metabolic panel, complete blood count, liver function tests, arterial blood gas).

See if able to build a prediction model for each one of these

base_name	component_name
BUN	UREA NITROGEN,SER/PLAS
CA	CALCIUM, SER/PLAS
CL	CHLORIDE, SER/PLAS
CO2	CO2, SER/PLAS
CR	CREATININE, SER/PLAS
GLU	GLUCOSE, SER/PLAS
K	POTASSIUM, SER/PLAS
NA	SODIUM, SER/PLAS

ALB	ALBUMIN, SER/PLAS
ALKP	ALK P\'TASE, TOTAL, SER/PLAS
ALT	ALT (SGPT), SER/PLAS
AST	AST (SGOT), SER/PLAS
DBIL	CONJUGATED BILI
IBIL	UNCONJUGATED BILIRUBIN
TBIL	TOTAL BILIRUBIN
TP	PROTEIN, TOTAL, SER/PLAS

WBC	WBC
HGB	HEMOGLOBIN
PLT	PLATELET COUNT

PHA	PH (A)
PCO2A	PCO2 (A)
PO2A	PO2 (A)

**Comment by sxu11** [comment]
Done the following ones (according to the components listed the other day in Slack): 'WBC', 'HGB', 'PLT', 'NA', 'K', 'CL', 'CR', 'BUN', 'GLU', 'CO2', 'CA', 'HCO3', 'TP', 'ALB', 'ALKP', 'TBIL', 'AST', 'ALT', among which 'HCO3' does not have sufficient associated patients. 

Results uploaded to Box/lab-normality-prediction-pipeline/Component_Predictions. 

Still need to do 'DBIL', 'IBIL', 'PHA', 'PCO2A', 'PO2A'.

**Comment by sxu11** [comment]
Done with Box/lab-normality-prediction-pipeline/Component_Predictions/'DBIL', 'IBIL', 'PHA', 'PCO2A', 'PO2A'.
