### ISSUE TITLE
Redraft manuscript to cater to JAMA IM (clinical) readers

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#182]
Drop flowchart figures in favor of basic table 1 type info. 
Move explanatory variables chart to appendix.

Avoid "Predictability[99]" and try rephrasing or adding common measures like sensitivity, specificity, ROC AUC, PPV, NPV, Likelihood ratios.

**Comment by sxu11** [comment]
Submitted on 03/01/2019.
