### ISSUE TITLE
Patch GI Bleed Consult Block Dead End State - State Transition Diagram Tool?

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#190]

**Comment by jonc101** [comment]
Patients were stuck in state 15 (bleeding out) prematurely triggered by early GI consult. FFP wouldn't get patient out of that state.
Will add FFP transition states from 15 (bleeding out) to 16 (coags okay) as an escape. Even though is optimistic, because that fixes patient's Hgb level too.
Also remove transition to code blue, as maybe too harsh a representation.

**Comment by jonc101** [comment]
Some extra rare Transfuse FFP and Transfuse RBC orders, but sometimes this is what people pick when they are searching for options. Need to add those as valid state transition triggers.

**Comment by JonathanChiang** [comment]
David made these changes
