### ISSUE TITLE
Add Recording for Sim Clinical Case Points

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#191]
For each clinical order a user enters in a clinical case simulation, record how many "points" each is worth.
Should not need to separately record each user's accumulated points when able to backtrack from sim_patient_order record of what the users ordered (and in which states)

**Comment by jonc101** [comment]
Fill in with recommender association templates for likely candidates that need scoring

**Comment by jonc101** [comment]
Plan to just use the sim_patient_order record, and be able to devise grading scheme off of those, rather than a separate recording.
Hwoever, have JSON user-click recordings, not for grading, but for metrics on usage

**Comment by JonathanChiang** [comment]
closing: above is addressed in (247)[https://github.com/HealthRex/CDSS/issues/247]
