### ISSUE TITLE
Review Google Cloud Infrastructure and migrate online compute here

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#193]
STARR, PHS and other data sources here use Google Cloud Platform as basis. Look into migrating over compute here for equivalent AWS functions (primarily EC2 Linux on-demand compute instances, as well as their data sharing ?bitbucket? and BigQuery SQL equivalent for rapid queries?)

**Comment by JonathanChiang** [comment]
Am I looking into how to use google cloud tools such as bitbucket/biqquery, or figure out which is the aws equivalent?

**Comment by jonc101** [comment]
Bitbucket / bigquery are Google cloud tools we’ll probably be using, but I’m not that familiar how to use them.

**Comment by jonc101** [comment]
[ ] Figure out the billing structure for this system. Where does the bill go to, how does it get paid for, how much do different services and typical usage cost?

**Comment by JonathanChiang** [comment]
I will close this ticket and make new one for nero migration
