### ISSUE TITLE
Make one new simulation case function (E.g., meningitis)

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#195]
○ David: Inserted meningitis case and tested run through
		○ [ ] Debug Internal Server Error -> Create Group Strings to categorize things like CSF results
		○ [ ] Abnormal lab results for initial presentation? WBC, lactate?
			□ Result flags for abnormal values as well
			□ Actually, unlikely to need to add sim_result or sim_order_result_map entries. Look for existing ones, and then just add the sim_state_result entries that specify what values each state should generate.
			□ [ ] Make simulation generate abnormal lactate result as an example
			□ [ ] Make it generate abnormal CSF studies, which may require adding "default" normal CSF study values (sim_state_id=0)
			□ [ ] Verify can transition state by ordering appropriate antibiotic
		○ [ ] Physical Exam for initial presentation
		○ [ ] Progress note immediate trigger after state transition?
	○ Jonathan
[ ] Separate "old" database up to 2014 with simulation cases, from up to 2017 database.

**Comment by JonathanChiang** [comment]
[Done ] Separate "old" database up to 2014 with simulation cases, from up to 2017 database.
