### ISSUE TITLE
Remove changing LOCAL_TEST_DB_PARAM in test cases, or revert in tearDown, otherwise breaks batch unit tests

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#198]
Trying to run all unit tests (e.g., python -m unittest discover -v -s medinfo -p "Test*.py") generates a bunch of excess errors:

ProgrammingError: syntax error at or near "."
LINE 1: DROP DATABASE UMich_test.db
                                ^

Because I think the TestFeatureMatrixFactory_UMich.py script gets run, and changes some of the test db parameters. I tried moving these to test setup and teardown, but still didn't completely eliminate the issue.

**Comment by sxu11** [comment]
ok will look into that later

**Comment by jonc101** [comment]
I think the answer is to put the DB_PARAM change and restore outside of the DBTestCase.setUp and .tearDown superclass calls, since those require the info.

Jonathan
