### ISSUE TITLE
Cleanup shifted_dt_tm to shifted_record_dt_tm consistency in stride_flowsheet 

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#199]
[ ] Look for anywhere in the code (e.g., Feature Matrix Factory)
[ ] Schema file under stride/psql
[ ] Data file in Box (medinfo_2008_2017) has a 1GB dump file of the flowsheet data, but it uses shifted_dt_tm instead. 
[ ] Remind people that they may need to update rename their local DB column.
   [ ] More so, the Amazon Web Server copies of the database must have the same usage as well. If requires changing, then recreate the respective machine images and RDS instances.

**Comment by sxu11** [comment]
Done. stick to shifted_dt_tm everywhere. People should use the updated "stride-inpatient-2008-2017-postgresql-indexed" AMI on AWS. Keep the last robust version of AMI (properly named) for 3 weeks in case any error occurs.
