### ISSUE TITLE
Update AWS EC2 instance with Git code update, including LocalEnv.py revisions

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#206]
LocalEnv.py was revised to be expected to include designation of database connection options. The snapshot machine images on AWS still have old style, so if do a git pull, will become inconsistent. Modify one of those with a properly updated LocalEnv.py file, then update the machine image snapshot.

**Comment by sxu11** [comment]
Is it better to modify LocalEnv.py or set default database values in medinfo.db.Env.py?

**Comment by jonc101** [comment]
I originally put it in medinfo.db.Env.py, but then Santhosh created and moved bunch of other stuff to LocalEnv.py.
For consistency, let’s just keep in LocalEnv.py for now.

**Comment by sxu11** [comment]
ok. just updated AMI on AWS.
