### ISSUE TITLE
Clinical Simulation UI - Test case for orders that yield multiple results delayed over time (e.g., CT prelim and then final result)

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#207]
Default all bigger imaging tests (e.g., CT, US, MRI) as delayed result by 1 hour but yield initial immediate result of test pending.

**Comment by JonathanChiang** [comment]
Jonathan Chen and David Morales updated test case orders for CT Head delay in working meeting 4-11-2019
