### ISSUE TITLE
Sim UI - Add Direct Synchronized DC Cardioversion as option associated with Afib/Dysrhythmia

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#208]
In real life, people just do this with their hands, no order_proc gets recorded so no clinical_item event to represent it. Create a respective clinical_item entity and some clinical_item_association records so that it will get suggested in Afib/Dysrhymthia example.

**Comment by JonathanChiang** [comment]
could we discuss more about clinical_item_association tables and their relations?

**Comment by JonathanChiang** [comment]
Jonathan Chen + David updated DC cardioversion with latest github push in working meeting yesterday
