### ISSUE TITLE
Simulation User Interface Updates 

### ISSUE THREAD

**Issue by JonathanChiang** [HealthRex/CDSS#225]
- [x] concrete project github 
- [x] update script (consent, pay, 0 case (uninitialized-demo))
- [x] look into additional content (uncertain) 
- [x] gi bleed (prospect to add or make improvements) (state transitions) 
- [x] figure a way to prompt the end of the case ["scripted" "note when they final state for consistency", "priming for consistency"]
- [x] removing numerical value from recommender (confusing and/or distracting) 
- [x] duplicate note (state 40) (side state?? auxiliary state??) (sub-progress note??)
- [x] timestamp confusion on similar notes (ordered together) (discussion??? design???)
- [x] maintain 40 + minutes content as benchmark??? (prospectively Jason + Lisa + Ron??)

**Comment by JonathanChiang** [comment]
- [ ] update general notes (to prompt over, and direct cardioversion that says when the electrical shock happended and result for that patient feels improved)

**Comment by JonathanChiang** [comment]
- [ ] explore recommender change triggers for initial diagnosis

**Comment by JonathanChiang** [comment]
Find the actual values for each sim_state that corresponds to the "end of the case"

**Comment by jonc101** [comment]
[x] Added function so users can search for related orders directly based on individual orders from Order History
[x] Added notes to some of the last step notes that "Admitting team on the way" to help signal to user they can start to wrap up the case.

**Comment by JonathanChiang** [comment]
Focus on Testing all the user updates

**Comment by JonathanChiang** [comment]
- [ ] Test GI Bleed for Terminal Case 
- [ ] Look at DB for Patient Sim States 
- [ ] Review Shortness of Breath Case and Testing 
- [ ] Test Json for data analysis (ask david for help) 
- [ ] Ensure we send preliminary email to Chief Resident at Stanford 
- [ ] Look through Diabetic Fatigue 
- [ ] Look through Meningitis Case 
- [ ] Look into making sure other physicians abstain from talking about the case to reduce biasing results 
- [ ] Improve "Script" when physicians arrive 
- [ ] Have Paperwork ready for each Physician 
- [ ] Have Google Forms Ready (may include questions about order sets) (Mixed Method Study)
- [ ] Try to find any bugs preemptively
