### ISSUE TITLE
Create Postgres Server 

### ISSUE THREAD

**Issue by JonathanChiang** [HealthRex/CDSS#230]

**Comment by JonathanChiang** [comment]
- [ ] Setup WIndows Server 
- [ ] Configure Postgres Environment

**Comment by JonathanChiang** [comment]
Bigfix is being annoying. installed but wrong version

**Comment by JonathanChiang** [comment]
Trying to reproduce Postgres Server on my personal windows/system/server

**Comment by JonathanChiang** [comment]
- [ ] Install box tools to get clinical item data 
- [ ] setup postgres med-info table 
- [ ] git clone repo windows system

**Comment by JonathanChiang** [comment]
**BLOCKED** 

Need a copy of windows pro to get bitlocker to get encryption on my system.

**Comment by JonathanChiang** [comment]
Installed Windows Pro 2 days ago.

**Comment by jonc101** [comment]
Given finite number of test cases, will probably just run tests off Jonathan's laptop for now, unless plan to expand later. Just have to remember to dump and git push database each time.
