### ISSUE TITLE
Collect Stats on Common Referral Diagnoses vs. Use of Respective Order Set

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#234]
See Song's prelim work on finding the most common diagnoses associated with referrals to see specialists.

Look in the proc_orderset (or med_orderset) tables for usages of existing order set checklists, particularly protocol_name (other info is more detailed sub-levels) where starts with "AMB" to indicate usage in Ambulatory (outpatient) settings, as opposed to IP (Inpatient).

Want to show a small table in grant proposal showing how often people are requesting help for scenarios/diagnoses, yet very few times are they using the preconstructed order set checklists. (E.g., thousands of referrals for diabetes but only hundreds of diabetes checklist usages. Hundreds of referrals for anemia, but only few dozen use of checklist. Referrals for platelet/brusing problem, but no matching order set checklist exists at all.)

Will require some manual mapping between referral diagnosis and respective checklist that likely matches, so don't do this exhaustively. Maybe just do top referral diagnoses for Hematology and Endocrine and pick out the handful where can find a respectively matching orderset.

**Comment by JonathanChiang** [comment]
- [ ] Review Proc Order-set Table 
- [ ] Get review on thousands of orders 
- [ ]  Review Order Sets with AMB

**Comment by JonathanChiang** [comment]
- [ ] Start Monday Morning

**Comment by JonathanChiang** [comment]
**Jonathan Chen** 

Something like that, but probably more involved than even necessary. This is just basic descriptive stats to illustrate the potential opportunity
I would just generate a count of the top diagnoses that get referrals

Then look for respective AMB order sets that match each of those diagnoses
Compare the count of how often the referral diagnosis happens vs. how many times the respective AMB order set is ever used
(Maybe restrict to just primary care docs, but first pass, don't even have to bother with that)
You'll probably find hundreds of referrals for Hyperthyroidism, but only dozens of usage of the Hyperthyroidism order set

**Comment by JonathanChiang** [comment]
"""

SELECT
  a.jc_uid, a.pat_enc_csn_id_coded, a.description,  a.ordering_date_jittered as date,
  dc.dx_id, dc.dx_name,
  po.protocol_name, po.ss_sg_name
FROM   
    `datalake_47618.order_proc` as a,
    `datalake_47618.diagnosis_code` as dc, 
    `datalake_47618.proc_orderset` as po 
    
WHERE 
  description like "%REFERRAL TO HEMATOLOGY%" 

#and  ordering_date_jittered > '2014-01-01'
and  dc.pat_enc_csn_id_coded = a.pat_enc_csn_id_coded 
and dc.pat_enc_csn_id_coded = po.pat_enc_csn_id_coded 
and po.protocol_name like "AMB%"
ORDER BY 
  ordering_date_jittered
                    
"""
