### ISSUE TITLE
Update BigQuery Wiki 

### ISSUE THREAD

**Issue by JonathanChiang** [HealthRex/CDSS#238]

**Comment by JonathanChiang** [comment]
- [ ] Work with Star to Come up with Wiki

**Comment by cl93106** [comment]
"How to" stating point:
https://cloud.google.com/bigquery/docs/how-to

**Comment by cl93106** [comment]
https://github.com/HealthRex/CDSS/wiki/Google-BigQuery-API-and-scripts
