### ISSUE TITLE
Clinical UI Usage Reports 

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#240]
**Generate preliminary usage reports and then design upgrades/patches based on what's desired**
Example stats of interest
- Total number of order options presented through
  - Manual search
  - Related orders (Common list vs. Specific list vs. individual related order link)
- Total number of orders signed that came from each of the above
- Total number of orders that were presented in one of the related order lists, but was chosen manually subsequently instead
- Time
  Time for total case completion
  Total number of button clicks?
     Number of manual searches done, number of times swapping between notes, and results review

- [ ] Verify that order set usage stats are being collected
  Looks like only in "v5" of UI tracker. Probably wasn't recorded for first ~20 users.

- [ ] Convert first 10 user records so have total >40. 
- [ ] Inspect to see if order set usage is available for any/all. 
- [ ] Inspect to see if able to differentiate which half of the recommender list people were using more ("common" vs. "related" orders)

**Comment by JonathanChiang** [comment]
- join data on survey (physician data (user id, case, grade) have to link user with physician 
- [ ] be able to cross reference survey 
- [ ] not able to capture points over time (merge json)

**Comment by JonathanChiang** [comment]
- [ ] manually validate script with videos to ensure sanity of usage report feedback
