### ISSUE TITLE
Expand Recruitment Process  - Send out recruitment messages - Schedule people into slots - Gift Cards - #Estimate: 1 day, #Due: 6/24/2019

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#241]
Once testing process/pipeline refined, expand user recruitment, implementing randomization for different subcases.

Kind of happening already with more people lined up to test. Will expand invite list to ER docs and other residents and hospitalists as needed.

- [x] 6/18/2019 - Invite emails sent to ER docs, Dan Fang (VA Hospitalists), Phil Lee + Brooke Cotter (PAMF Hospitalists), BAMIS mailing list.

- [...] 7/1/2019, if haven't gotten 10-15 people already scheduled, then expand recruitment.
  - 7/9/2019 - Recruitment email sent to new Chiefs to circulate with new R3s
- 7/15/2019 - We have 35 done, 5 more scheduled this week.

**Comment by JonathanChiang** [comment]
- [ ] Plan for July for Recruitment Expansion (new residents arrive)

**Comment by JonathanChiang** [comment]
In progress: 
- physicians already signing up

**Comment by JonathanChiang** [comment]
probably send out one more reminder on Friday
