### ISSUE TITLE
Sim Ui Manuscript 

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#244]
Collate results of broader study (~50 participants?) and write-up into manuscript (option for conference proceeding)

Maybe split into
- [ ] Conference Paper (AMIA Symposium?)
- Grading and basic usage stats? or Just one?

- [ ] Journal Paper (JAMIA as a follow-up to OrderRex)
- Grading and more usage stats and qualitative interpretation

**Comment by JonathanChiang** [comment]
- [ ] work on grading with Andre Kumar? Methodolgy

**Comment by JonathanChiang** [comment]
- [ ] Conference Submission? https://healthrecsys.github.io/2019/
