### ISSUE TITLE
Google Big Query copy of Stride Inpatient 2008-2017 

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#246]
Make copy of STRIDE Inpatient 2008-2017 database onto Google BigQuery infrastructure

**Comment by JonathanChiang** [comment]
- [ ] Getting Star Access to SUNET and EMAIL: which will enable Stanford Mining Clinical Decisions Access 
- [ ] Getting Star Access to Laptop?

**Comment by JonathanChiang** [comment]
- [ ] https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/get
- [ ] schema detection in python?

**Comment by JonathanChiang** [comment]
- [ ] Getting box access to data (for Star)

**Comment by JonathanChiang** [comment]
- [ ] https://github.com/HealthRex/CDSS/blob/master/scripts/DevWorkshop/GoogleCloudPlatform/auth_cloud.py

**Comment by JonathanChiang** [comment]
- [ ] Review Google CLI tools for developer solutions:

https://cloud.google.com/bigquery/docs/bq-command-line-tool

**Comment by cl93106** [comment]
Using Python instead of CLI
Scripts WIP:
https://github.com/HealthRex/CDSS/blob/master/scripts/GoogleCloud/BQ/BigQueryConnect.py

**Comment by cl93106** [comment]
34 tables uploaded to BQ stride_2008_2017 dataset
- [ ] Run test queries
- [ ] Use visualizer tool to create diagram

**Comment by cl93106** [comment]
- [ ] check row counts


table_name | local_count | bq_count
-- | -- | --
stride_2008_2017.backup_link_patient_item | 0 | 0
stride_2008_2017.clinical_item | 73227 | 73227
stride_2008_2017.clinical_item_association | 3425981 | 3425981
stride_2008_2017.clinical_item_category | 200 | 200
stride_2008_2017.clinical_item_link | 90 | 90
stride_2008_2017.collection_type | 5 | 5
stride_2008_2017.data_cache | 2 | 2
stride_2008_2017.item_collection | 13849 | 13849
stride_2008_2017.item_collection_item | 46982 | 46982
stride_2008_2017.order_result_stat | 1681 | 1681
stride_2008_2017.patient_item | 95526151 | 95526151
stride_2008_2017.patient_item_collection_link | 9853151 | 9853151
stride_2008_2017.stride_admit | 77499 | 77499
stride_2008_2017.stride_adt | 916017 | 916017
stride_2008_2017.stride_chargemaster | 45092 | 45092
stride_2008_2017.stride_culture_micro | 354899 | 354899
stride_2008_2017.stride_drg | 144845 | 144845
stride_2008_2017.stride_dx_list | 2494911 | 2494911
stride_2008_2017.stride_flowsheet | 78226917 | 78226917
stride_2008_2017.stride_icd9_cm | 40846 | 40846
stride_2008_2017.stride_income | 116656 | 116656
stride_2008_2017.stride_io_flowsheet | 251730173 | 251730173
stride_2008_2017.stride_mapped_meds | 13918 | 13918
stride_2008_2017.stride_medication_mpi | 2823 | 2823
stride_2008_2017.stride_note | 8881912 | 8881912
stride_2008_2017.stride_order_med | 10578855 | 10578855
stride_2008_2017.stride_order_medmixinfo | 2137809 | 2137809
stride_2008_2017.stride_order_proc | 72264650 | 72264650
stride_2008_2017.stride_order_results | 64382854 | 64382854
stride_2008_2017.stride_orderset_order_med | 3395541 | 3395541
stride_2008_2017.stride_orderset_order_proc | 9682901 | 9682901
stride_2008_2017.stride_patient | 116656 | 116656
stride_2008_2017.stride_patient_encounter | 243223 | 243223
stride_2008_2017.stride_preadmit_med | 209856 | 209856
stride_2008_2017.stride_treatment_team | 4203991 | 4203991
