### ISSUE TITLE
Manual validation of a couple data rows from merged case data to confirm if any collection misinterpretations - #Estimate: 1 day, #Due: 6/26/2019

### ISSUE THREAD

**Issue by JonathanChiang** [HealthRex/CDSS#255]
data to confirm if any collection misinterpretations - 1 day

check to see if it confirms with video 

Spot check a couple random cases of a couple random doctors and validate against automated report generation for consistent measures. May get Star incorporate.

**Comment by cl93106** [comment]
Cross-checking video vs. tracker data (v4)
Tracker data compared:
- sim_analyzer.event_tracker_data
- sim_analyzer.results_tracker_data
- sim_analyzer.signed_orders_collections

Cases compared so far:
34_159 (kh10)
34_158 (kh10)
34_157 (kh10)
50_170 (r23)

**Comment by JonathanChiang** [comment]
Initial validation completed:
