### ISSUE TITLE
Automated UI Test Grader that accounts for grouping of options - #Estimate: 3 days, #Due: 6/26/2019

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#262]
E.g., If a patient gets ceftriaxone or cefepime, either could be worth 10 points, but shouldn't give a user 20 points for doing both. Have grader be able to apply basic and this kind of logic.

Have respective unit test to verify

Suggested:
- Create another table in the SQL database, called sim_grading_key
  medinfo/cpoe/cpoeSim/simData/cpoeSim.sql
- Dump out an empty copy of the new table
  Modify the dump, restore, revert scripts in the same directory so they will start capturing this table as well.

- Add a function to SimManager.py, "gradeSimulatedCase", start by just writing the stub. Which is just the function name and what parameters (ID of the case/user, and which grading key to use)… leave content blank or copy prior implementation...

- Add test (can extent TestSimManager or copy it and make next version)…
  Copy or modify or make up fake simulated user data and grading key to test typical inputs but also predictable edge cases (E.g., same order CBC gets ordered multiple times in a row across multiple sim states. Or multiple orders from the same interaction group are ordered (e.g., multiple antibiotics) either within or across multiple states. Probably simplest way is to find these groups and only give points for the first one that occurs).

**Comment by JonathanChiang** [comment]
embed additional logic to the grader when summing points.

**Comment by JonathanChiang** [comment]
### Unit Test


- [ ] Create another table in the SQL database, called sim_grading_key
medinfo/cpoe/cpoeSim/simData/cpoeSim.sql

- [ ] Dump out an empty copy of the new table

- [ ] Modify the dump, restore, revert scripts in the same directory so they will start capturing this table as well.

- [ ] Add a function to SimManager.py, "gradeSimulatedCase", start by just writing the stub. Which is just the function name and what parameters (ID of the case/user, and which grading key to use)… leave content blank or copy prior implementation...

- [ ] Add test (can extent TestSimManager or copy it and make next version)…
- [ ] Copy or modify or make up fake simulated user data and grading key to test typical inputs but also predictable edge cases (E.g., same order CBC gets ordered multiple times in a row across multiple sim states. 
- [ ] Or multiple orders from the same interaction group are ordered (e.g., multiple antibiotics) either within or across multiple states. Probably simplest way is to find these groups and only give points for the first one that occurs).

**Comment by JonathanChiang** [comment]
need to finalize function on real data and grades
