### ISSUE TITLE
Clinical Item data conversions for STARR Data Lake 2018 database

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#267]
Adapt inpatient data converters to the broader STARR Data Lake 2018 to translate most major patient clinical events into discrete clinical_item events in a mass patient_item event log.

Will require testing and adapting existing medinfo.dataconversion.STRIDEXXXConversion.py programs as well as considering new ones for new data types
[ ] ADT
[ ] Micro Culture (adapt from Conor's work)
[ ] Encounters
[ ] Order Set usage?

Notes for Star 7/26/2019
• [ ] Create schema of patient_item, etc. under a new database section "clinical_item2018"
    • [ ] Create a respective TestSTARRDemographicsConversion first…
    • [ ] Create a version of STARRDemographicsConversion that takes input from BigQuery database but outputs to local PostgreSQL database
        ○ First do end-to-end process for just Demographics and TreatmentTeam, save the other table conversion for after
            § [ ] Upload stride_mapped_meds to the BigQuery database
            § … Start doing the same for bigger tables like OrderMed and OrderProc
            § … May need help with some of this (particularly OrderMed and mappings), if there's different types of data that need to reconcile the conversion process
            § … Coordinate with Conor on the CultureMicro conversion, which should get some revisions in new version
            § Those will be large tables, so make sure they can be batched (e.g., do 1 year of data at a time)
            § [ ] Add more conversion for note metadata and other data types???
    • [ ] Promote BigQuery connection modules to core application directory (medinfo/dataconversion or medinfo/db/BigQuery)
        ○ [ ] Respective unit tests for behavior
    • [ ] Upload batches of patient_item, etc. data to BigQuery copy
        ○ [ ] Respective tests that can upload a few batches in a row
[ ] Wrapper script around above, so then just run every conversion in batches and upload them as go. Related: You'll likely need to delete your local patient_item table contents to free hard drive space. But keep clinical_item table complete. Patient_item_Id_seq should still retain a consistent value.

**Comment by cl93106** [comment]
- [ ] order_proc conversion (work-in-progress)

**Comment by ynodir** [comment]
[x] demographic conversion
[x] treatment_team conversion

**Comment by ynodir** [comment]
FYI, might need to go through the conversions again once the UTC->PT and `timestamp` -> `date` conversions.

**Comment by ynodir** [comment]
> 
> 
> FYI, might need to go through the conversions again once the UTC->PT and `timestamp` -> `date` conversions are done.

Fixes are merged above.

**Comment by ynodir** [comment]
In progress:
- [] `order_med` conversion

**Comment by ynodir** [comment]
Patient IDs file used for `starr_datalake2018.demographic` conversion:
[starr_demographics_conv_patient_ids.zip](https://github.com/HealthRex/CDSS/files/4468897/starr_demographics_conv_patient_ids.zip)
