### ISSUE TITLE
Automated grading of cases, given expert panel scores. Use fake scores first. - Adapt to Python for automation and unit test verification - #Estimate: 3 days, #Due: 6/27/2019

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#272]

**Comment by JonathanChiang** [comment]
- [X] Status: Automatically Grades Given Scores from Dr. Chen:
- Making new ticket: to double check and quality inspection: hand checking and adding additional unit tests from JChen's scores. 


thanks,
Jonathan Chiang
