### ISSUE TITLE
Comprehensive Suite of Tools For Clinical Recommender #Due: 7/4/2019

### ISSUE THREAD

**Issue by JonathanChiang** [HealthRex/CDSS#276]
- [ ] import data and task manager (python file) 
- [ ] import case generator 
- [ ] assign pipeline to box 
- [ ] read data from DB 
- [ ] pull grades from BOX 
- [ ] push grading key 
- [ ] pull tracker output / check order set 
- [ ] pull physician responses  from google response

**Comment by jonc101** [comment]
Not actively doing anymore
