### ISSUE TITLE
Import ALERTS datatable into BigQuery STARR_datalake2018

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#287]
See email notes from Yelena from RIC on getting the datatable from bitbucket and then get into BigQuery database.

Double check proper interpretation of datetime / timestamps so not getting mixed up on relative times compared to other data elements in patient records.

**Comment by cl93106** [comment]
62364707 rows added to alert_2019.alert table
Assuming standard offset (-8) vs. UTC (as opposed to DST)
Appended local_update_date_jittered datetime column

**Comment by cl93106** [comment]
Corrected update_date_jittered column to account for DST
