### ISSUE TITLE
Migrate starr_datalake2018 from mining-clinical-decisions to som-nero-phi-jonc101 project

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#294]
To increase security around dataset and allow for PHI additions, migrate to VPC secured project
Accumulated access notes:
https://github.com/HealthRex/CDSS/wiki/Google-BigQuery-Access

	• Flowsheet migrate to Nero
		○ See if can transfer permissions or copy all online
		○ Otherwise need to export - import data via local connection, but 2B rows of data!?
Afterwards, want to drop the text value column. Try adding numerical columns first to parse the first two numerical values in the text column?

**Comment by cl93106** [comment]
- [ ] make a copy of flowsheet table to som-nero
- [ ] Enable transfer API in som-nero
- [ ] resolve policy error when attempting dataset/table copy

**Comment by cl93106** [comment]
Tables:

- [ ] adt
- [ ] allergy
- [ ] clinical_doc_meta
- [ ] culture_sensitivity
- [ ] demographic
- [ ] dep_map
- [ ] diagnosis_code
- [ ] drg
- [ ] drg_code
- [ ] encounter
- [ ] family_hx
- [ ] flowsheet
- [ ] lab_result
- [ ] mar
- [ ] med_orderset
- [ ] ndc
- [ ] ndc_code
- [ ] order_med
- [ ] order_proc
- [ ] path_report_meta
- [ ] proc_orderset
- [ ] procedure_code
- [ ] prov_map
- [ ] radiology_report_meta
- [ ] social_hx
- [ ] treatment_team
