### ISSUE TITLE
Patch starr_testing.shc_access_log_de timefields

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#300]
[ ] Rename existing TIMESTAMP columns into "_utc" suffix, while 
[ ] replacing columns with DATETIME fields that represent local (US/Pacific) timezone.

[ ] Rename 'starr_testing' dataset to 'starr_access_log'

**Comment by ynodir** [comment]
- [X] Rename existing TIMESTAMP columns into "_utc" suffix, while
- [X] replacing columns with DATETIME fields that represent local (US/Pacific) timezone.

[ ] Rename 'starr_testing' dataset to 'starr_access_log'

**Comment by ynodir** [comment]
Executed SQL script:
```
CREATE OR REPLACE TABLE `starr_testing.shc_access_log_de` AS
SELECT
  * EXCEPT (access_time_jittered),
  access_time_jittered as access_time_jittered_utc,
  datetime(access_time_jittered, 'America/Los_Angeles') as access_time_jittered
FROM
  `starr_testing.shc_access_log_de`;
```

**Comment by ynodir** [comment]
Dataset rename is done according to: https://cloud.google.com/bigquery/docs/copying-datasets
Dataset `starr_access_log` is created as a copy of `starr_testing`.
Old `starr_testing` dataset is removed along with data transfer job used.
