### ISSUE TITLE
Patch alert table  timefields (same pattern. _utc timestamps, datetime for local time).

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#302]
Should be same datetime structure as our other tables.
I believe this is copied in both the som-nero-phi-jonc101 and mining-clinical-decisions starr_datalake2018 datasets.

**Comment by ynodir** [comment]
- [X] rename field in `som-nero-phi-jonc101.alert`: `update_date_jittered` -> `update_date_jittered_utc` and `local_update_date_jittered` -> `update_date_jittered`
- [X] rename field in `mining-clinical-decisions.alert`: `update_date_jittered` -> `update_date_jittered_utc` and `local_update_date_jittered` -> `update_date_jittered`

**Comment by ynodir** [comment]
Executed script for both projects:
```
create or replace table starr_datalake2018.alert
as
select * except(
  update_date_jittered,
  local_update_date_jittered
  ),
  update_date_jittered as update_date_jittered_utc,
  local_update_date_jittered as update_date_jittered
from starr_datalake2018.alert;
```
