### ISSUE TITLE
Find Data Set access for prescribing information from different countries for indication-prescription rate information

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#314]

**Comment by JonathanChiang** [comment]
relevant papers list: 
[prescription](https://pubmed.ncbi.nlm.nih.gov/29159797-correlation-of-opioid-mortality-with-prescriptions-and-social-determinants-a-cross-sectional-study-of-medicare-enrollees/?from_term=Grigoras+CA&from_cauthor_id=29159797&from_pos=1)

**Comment by JonathanChiang** [comment]
[CDC WONDER database](https://wonder.cdc.gov/)

**Comment by JonathanChiang** [comment]
European insurance industry database

**Comment by JonathanChiang** [comment]
[Methods: In Queensland, all opioid prescriptions (S8 prescriptions) dispensed by community pharmacies must be submitted to the Drugs of Dependence Unit (DDU). This potentially comprises a 'gold standard' against which other data sources may be judged. There are two national data sources: the Pharmaceutical Benefits Schedule (PBS) for all medications subsidised by government](https://pubmed.ncbi.nlm.nih.gov/23551471-prescribing-databases-can-be-used-to-monitor-trends-in-opioid-analgesic-prescribing-in-australia/)

**Comment by JonathanChiang** [comment]
[The Use of Prescription Claims Databases in Pharmacoepidemiological Research: The Accuracy and Comprehensiveness of the Prescription Claims Database in Québec](https://pubmed.ncbi.nlm.nih.gov/7775999-the-use-of-prescription-claims-databases-in-pharmacoepidemiological-research-the-accuracy-and-comprehensiveness-of-the-prescription-claims-database-in-quebec/)

**Comment by JonathanChiang** [comment]
Prescription pattern monitoring studies (PPMS)

**Comment by JonathanChiang** [comment]
gained a lot  of insight  from  Suzanne Tamang  about international data access  specifically for  opioid. Jon Chen will speak to her about specific  details or potential project collabs.
