### ISSUE TITLE
Update STARR datalake tables

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#318]
https://console.cloud.google.com/storage/browser/jc_data_bucket

- [x] culture_sensitivity table in STARR datalake with completed data from 2015 forwards
- [x] alerts table

- [x] LPCH childrens data

- [x] 2019 update of STARR_datalake

- [x] Flowsheet number extraction

- [x] Copy deidentified version to mining-clinical-decisions

**Comment by jonc101** [comment]
I think this issue can be closed now, as the deID version has since been copied to mining-clinical-decisions, including extracted flowsheet numbers?

**Comment by ynodir** [comment]
@jonc101 yes, it should be done now. I'm closing this issue.
