### ISSUE TITLE
Develop additional simulation cases to span specialties and specificity

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#48]
[ ] Setup authoring worksheet and example (GI Bleed) so clinical collaborators can follow suit

E.g., Some highly protocolized (e.g., neutropenic fever) vs. some vague diagnostic cases (e.g., altered mental status)

See Isabel evaluation for example setup, though looks largely idiosyncratic custom authoring.
https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/1472-6947-6-22

Otherwise do more web searching for differing simulation cases (e.g., Medscape education simulation cases or NEJM clinical case reviews, etc.)

**Comment by JonathanChiang** [comment]
Can we close this issue? Since we have 5 cases and can loop content?

**Comment by jonc101** [comment]
Yeah, I think it’s fine.
