### ISSUE TITLE
Develop "reference standard" for scoring quality of decision making for simulated cases

### ISSUE THREAD

**Issue by jonc101** [HealthRex/CDSS#49]
For simulated cases developed, work through with "clinical expert panel" to assign scores (positive or negative) for the most common and likely medical decisions / clinical orders.

Too laborious to score 2,000 possible choices, but do the most common up front and then go back and re-review after initial test runs to score any extra steps people took that were not expected.
Probably need scoring per phase/state of each simulation.

TBD: Define a scoring rubric so different experts can aim for some kind of consensus?

- Allow record of each case and each expert and each decision, what points to assign for each
   - This should allow for reconciling or averaging multiple votes.
- Allow grading of points for a choice no matter which state a patient is in. Only if patient in a given state or timing / sequence of choice. For example, ordering CT Head for meningitis not necessarily wrong, but if wait until result to start antibiotics, then wrong.
- Only getting points once if multiple satisfactory choices (e.g., multiple antibiotic options).

Design such that can be stored in a spreadsheet, or better yet, a new "sim_" table in SQL database, so can then just run some simple application code to auto-grade all cases.

**Comment by JonathanChiang** [comment]
Closing this issue addressed in another issue
