### ISSUE TITLE
[starr][1] Design python core and db (psql, stata, etc.) drivers

### ISSUE THREAD

**Issue by SanthoshBala** [HealthRex/CDSS#97]

**Comment by SanthoshBala** [comment]
**Overview**
Extract code for (a) general I/O and (b) starr-specific I/O into separate repositories, so that it is easier for collaborators to start working on projects with an independent environment (e.g. clinical collaborators can use Stata for all their analyses).

**Python Core**
Python core handles business logic for converting raw tables into derived tables. Will require copying most modules and tests from `dataconversion` and optimizing their performance (Santhosh suspects that we can improve `dataconversion` runtime by 10-100x by building some simple indices on the raw tables before running.

**Drivers**
Drivers handle both (a) general I/O utilities (e.g. SQLQuery.py and DBUtil.py), and (b) starr-specific I/O (e.g. turning python core output into stata tables). All of the general I/O utilities should be kept in separate repositories (e.g. CDSS/psql-io) to ensure that clients can use drivers without fetching all the other code.

**Initial Package Structure**
```
CDSS/
├── medinfo/
├── scripts/
└── (substate) starr/
   ├── core/
   └── drivers/
      ├── psql/
        ├── psql-conversion/
        └── (substate) psql-io/
      ├── stata/
        ├── stata-conversion/
        └── (substate) stata-io/
      └── r/
        ├── r-conversion/
        └── (substate) r-io/
```

**Comment by SanthoshBala** [comment]
@jonc101 – what do you think of this high level idea?

In general, I think we should be pushing to keep a monorepo, but in this particular case I think it makes sense to split off some of the functionality so that it's easier for us to fetch/run/test that code separately, and easier for others to use `starr` repo for independent other analyses.

If you think that's too much though, we could probably get 80% of the value by just refactoring CDSS to have this package structure (minus the substates). That'd still probably make it easier for people to start using the database locally for their own analyses.

**Comment by jonc101** [comment]
Not sure I fully follow the package structure. Think we should keep the monorepo, but could organize such that people could pull just one subdirectory that has only the parts they'll need for basic connection (e.g., just medinfo/db, common, and possibly dataconversion, without interest in the cpoe package).
